import type { Bookmark, Category, UI_View } from '../types/bookmark.types'

export const mockCategories: Category[] = [
  { id: '0', parent_id: '0', name: '🗂️ 전체보기' },
  {
    id: '1',
    parent_id: '0',
    name: '💻 개발',
    children: [
      {
        id: '2',
        parent_id: '1',
        name: 'React',
        children: [
          { id: '9', parent_id: '2', name: 'supabase' },
          { id: '10', parent_id: '2', name: 'TailwindCSS' },
        ],
      },
      { id: '3', parent_id: '1', name: 'CSS' },
      { id: '4', parent_id: '1', name: '인프라' },
    ],
  },
  {
    id: '5',
    parent_id: '0',
    name: '📚 공부',
    children: [
      { id: '6', parent_id: '5', name: 'Makerclub' },
      { id: '7', parent_id: '5', name: 'Wemake' },
    ],
  },
  { id: '8', parent_id: '0', name: '🚀 생산성' },
]

export const mockTabs: UI_View[] = [
  {
    id: 'tab-all',
    name: '전체',
    content_type_id: 'bookmark',
    ui_view_type_id: 'TAB',
    category_id: '0',
  },
  {
    id: 'tab-1',
    name: '💻 개발',
    content_type_id: 'bookmark',
    ui_view_type_id: 'TAB',
    category_id: '1',
  },
  {
    id: 'tab-2',
    name: '📚 공부',
    content_type_id: 'bookmark',
    ui_view_type_id: 'TAB',
    category_id: '5',
  },
]

export const mockBookmarks: Bookmark[] = [
  {
    id: '1',
    categoryId: '1',
    title: 'React 공식문서',
    url: 'https://react.dev',
    tags: ['React', 'Docs'],
    click_count: 5,
  },
  {
    id: '2',
    categoryId: '1',
    title: 'TailwindCSS',
    url: 'https://tailwindcss.com',
    tags: ['CSS', 'Framework'],
    click_count: 3,
  },
  {
    id: '3',
    categoryId: '1',
    title: 'ChatGPT',
    url: 'https://chat.openai.com',
    tags: ['AI'],
    click_count: 10,
  },
  {
    id: '4',
    categoryId: '2',
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    tags: ['Web', 'Docs'],
    click_count: 8,
  },
  {
    id: '5',
    categoryId: '2',
    title: 'TypeScript Handbook',
    url: 'https://www.typescriptlang.org/docs/',
    tags: ['TypeScript', 'Docs'],
    click_count: 6,
  },
  {
    id: '6',
    categoryId: '2',
    title: 'Node.js',
    url: 'https://nodejs.org',
    tags: ['Node.js', 'Backend'],
    click_count: 4,
  },
  {
    id: '7',
    categoryId: '2',
    title: 'Vercel',
    url: 'https://vercel.com',
    tags: ['Hosting', 'Cloud'],
    click_count: 2,
  },
  {
    id: '8',
    categoryId: '2',
    title: 'GitHub',
    url: 'https://github.com',
    tags: ['Git', 'Repository'],
    click_count: 9,
  },
  {
    id: '9',
    categoryId: '2',
    title: 'Notion',
    url: 'https://notion.so',
    tags: ['Productivity', 'Tool'],
    click_count: 7,
  },
  {
    id: '10',
    categoryId: '3',
    title: 'Figma',
    url: 'https://figma.com',
    tags: ['Design', 'Tool'],
    click_count: 1,
  },
  {
    id: '11',
    categoryId: '3',
    title: 'Velog',
    url: 'https://velog.io',
    tags: ['Blog', 'Dev'],
    click_count: 4,
  },
  {
    id: '12',
    categoryId: '3',
    title: 'Reddit Programming',
    url: 'https://reddit.com/r/programming',
    tags: ['Community', 'Forum'],
    click_count: 8,
  },
  {
    id: '13',
    categoryId: '3',
    title: 'Hacker News',
    url: 'https://news.ycombinator.com',
    tags: ['News', 'Startup'],
    click_count: 11,
  },
  {
    id: '14',
    categoryId: '3',
    title: 'CodePen',
    url: 'https://codepen.io',
    tags: ['Frontend', 'Sandbox'],
    click_count: 2,
  },
  {
    id: '15',
    categoryId: '3',
    title: 'Dev.to',
    url: 'https://dev.to',
    tags: ['Blog', 'Community'],
    click_count: 7,
  },
  {
    id: '16',
    categoryId: '3',
    title: 'Smashing Magazine',
    url: 'https://smashingmagazine.com',
    tags: ['Web', 'Design'],
    click_count: 3,
  },
  {
    id: '17',
    categoryId: '3',
    title: 'Can I use',
    url: 'https://caniuse.com',
    tags: ['Web', 'Compatibility'],
    click_count: 6,
  },
  {
    id: '18',
    categoryId: '3',
    title: 'W3Schools',
    url: 'https://w3schools.com',
    tags: ['Web', 'Learning'],
    click_count: 5,
  },
  {
    id: '19',
    categoryId: '4',
    title: 'MDX Docs',
    url: 'https://mdxjs.com',
    tags: ['MDX', 'Docs'],
    click_count: 2,
  },
  {
    id: '20',
    categoryId: '3',
    title: 'NPM',
    url: 'https://npmjs.com',
    tags: ['Package', 'Registry'],
    click_count: 9,
  },
  {
    id: '21',
    categoryId: '3',
    title: 'Yarn',
    url: 'https://yarnpkg.com',
    tags: ['Package', 'Manager'],
    click_count: 4,
  },
  {
    id: '22',
    categoryId: '3',
    title: 'Babel',
    url: 'https://babeljs.io',
    tags: ['JS', 'Compiler'],
    click_count: 3,
  },
  {
    id: '23',
    categoryId: '3',
    title: 'ESLint',
    url: 'https://eslint.org',
    tags: ['Lint', 'JS'],
    click_count: 6,
  },
  {
    id: '24',
    categoryId: '1',
    title: 'Prettier',
    url: 'https://prettier.io',
    tags: ['Format', 'JS'],
    click_count: 5,
  },
  {
    id: '25',
    categoryId: '1',
    title: 'Uptime Robot',
    url: 'https://uptimerobot.com',
    tags: ['Monitoring', 'Tool'],
    click_count: 1,
  },
  {
    id: '26',
    categoryId: '5',
    title: 'LeetCode',
    url: 'https://leetcode.com',
    tags: ['Algorithm', 'Coding'],
    click_count: 12,
  },
  {
    id: '27',
    categoryId: '5',
    title: 'freeCodeCamp',
    url: 'https://freecodecamp.org',
    tags: ['Learning', 'Web'],
    click_count: 5,
  },
  {
    id: '28',
    categoryId: '5',
    title: 'CSS-Tricks',
    url: 'https://css-tricks.com',
    tags: ['CSS', 'Tips'],
    click_count: 6,
  },
  {
    id: '29',
    categoryId: '5',
    title: 'Google Fonts',
    url: 'https://fonts.google.com',
    tags: ['Font', 'Design'],
    click_count: 3,
  },
  {
    id: '30',
    categoryId: '5',
    title: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    tags: ['Q&A', 'Community'],
    click_count: 15,
  },
  {
    id: '31',
    categoryId: '6',
    title: '메이커클럽 자소서',
    url: 'https://nomadcoders.notion.site/1ec0ac34463480b38589eb49339f11cd',
    tags: ['Notion', 'nomadcoders', 'makerclub'],
    click_count: 15,
  },
  {
    id: '32',
    categoryId: '6',
    title: '메이커클럽 lobby',
    url: 'https://nomadcoders.co/c/maker-club-2/lobby',
    tags: ['makerclub', 'nomadcoders'],
    click_count: 15,
  },
  {
    id: '33',
    categoryId: '7',
    title: 'class 마스터클래스',
    url: 'https://nomadcoders.co/maker-masterclass/lobby',
    tags: ['lectures', 'nomadcoders'],
    click_count: 30,
  },
  {
    id: '34',
    categoryId: '7',
    title: 'git wemake',
    url: 'https://github.com/nomadcoders/wemake/commits/master/',
    tags: ['wemake', 'nomadcoders'],
    click_count: 30,
  },
] 